#!/usr/local/bin/bash

# === Main Usage Function ===
main_usage() {
  echo_message "Usage: $0 <command> [options/arguments]"
  echo_message " "
  echo_message "Available Commands:"
  echo_message "  init          - Initialize bhyve-cli configuration."
  echo_message "  create        - Create a new virtual machine."
  echo_message "  delete        - Delete an existing virtual machine."
  echo_message "  install       - Install an operating system on a VM."
  echo_message "  start         - Start a virtual machine."
  echo_message "  stop          - Stop a running virtual machine."
  echo_message "  restart       - Restart a virtual machine."
  echo_message "  console       - Access the console of a VM."
  echo_message "  logs          - Display real-time logs for a VM."
  echo_message "  list          - List all configured virtual machines, their static configuration, and live status."
  echo_message "  autostart     - Enable or disable VM autostart on boot."
  echo_message "  modify        - Modify VM configuration (CPU, RAM, network, etc.)."
  echo_message "  clone         - Create a clone of an existing VM."
  echo_message "  info          - Display detailed information about a VM."
  echo_message "  resize-disk   - Resize a VM's disk image."
  echo_message "  export        - Export a VM to an archive file."
  echo_message "  import        - Import a VM from an archive file."
  echo_message "  template      - Manage VM templates (create, list, delete)."
  echo_message "  snapshot      - Manage VM snapshots (create, list, revert, delete)."
  echo_message "  suspend       - Suspend a running virtual machine."
  echo_message "  resume        - Resume a suspended virtual machine."
  echo_message "  vnc           - Connect to a VM's VNC console."
  echo_message "  iso           - Manage ISO images (list and download)."
  echo_message "  switch        - Manage network bridges and physical interfaces."
  echo_message "  stopall       - Stop all running virtual machines."
  echo_message "  startall      - Start all configured virtual machines."
  echo_message "  verify        - Verify the consistency and integrity of VM configurations."
  echo_message "  vmnet         - Manage isolated virtual networks for VMs."
  echo_message " "
  echo_message "For detailed usage of each command, use: $0 <command> --help"
}
